name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Install JSHint
      run: npm install jshint --global

    - name: Run JSHint
      run: |
        # This command finds all JavaScript files recursively and runs JSHint on them
        find ./giftlink-backend -name '*.js' -exec jshint {} +
        echo "Linted all the js files successfully"

    - name: Install ESLint
      run: npm install eslint --global

    - name: Run ESLint
      run: |
        # This command finds all JavaScript files recursively and runs ESLint on them
        find ./giftlink-backend -name '*.js' -exec eslint {} +
        echo "ESLint check completed"

  client_build:
    name: Build client
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Run build
      run: |
        cd giftlink-frontend
        npm install
        npm run build
        echo "Client-side build successfully"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # Update Node.js version here
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
